<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['user_certificates_app_description'] = 'Security certificates are used to secure various apps that you use on a day to day basis.';
$lang['user_certificates_app_name'] = 'Сертификат пользователя';
$lang['user_certificates_certificates'] = 'Сертификат';
$lang['user_certificates_certificates_not_available_for_this_account'] = 'Сертификаты пользователей доступны не для этой учетной записи.';
$lang['user_certificates_certificates_not_available_on_this_system'] = 'Извините, сертификаты безопасности не доступны на этой системе. Пожалуйста, обратитесь к вашему системному администратору для получения дополнительной информации.';
$lang['user_certificates_certificates_not_enabled_for_your_account'] = 'Извините, сертификаты безопасности не включены для вашей учетной записи.';
$lang['user_certificates_certificates_not_yet_initialized'] = 'Извените , система сертификатов безопасности еще не была инициализирована. Пожалуйста, обратитесь к вашему системному администратору для получения дополнительной информации.';
$lang['user_certificates_configuration_file'] = 'Файл конфигурации';
$lang['user_certificates_create_certificates'] = 'Создать сертификат';
$lang['user_certificates_initialize_certificate_help'] = 'Пожалуйста, укажите пароль для защиты сертификатов безопасности. Если вы забыли пароль, вы должны будете начать с новым набором сертификатов.';
