<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['user_certificates_app_description'] = 'Security certificates are used to secure various apps that you use on a day to day basis.';
$lang['user_certificates_app_name'] = 'User Certificates';
$lang['user_certificates_certificates'] = 'Certificates';
$lang['user_certificates_certificates_not_available_for_this_account'] = 'User certificates are not available for this account.';
$lang['user_certificates_certificates_not_available_on_this_system'] = 'Sorry, security certificates are not available on this system.  Please contact your system administrator for more information.';
$lang['user_certificates_certificates_not_enabled_for_your_account'] = 'Sorry, security certificates are not enabled for your account.';
$lang['user_certificates_certificates_not_yet_initialized'] = 'Sorry, the security certificates system has not yet been initialized.  Please contact your system administrator for more information.';
$lang['user_certificates_configuration_file'] = 'Configuration File';
$lang['user_certificates_create_certificates'] = 'Create Certificates';
$lang['user_certificates_initialize_certificate_help'] = 'Please specify a password for protecting your security certificates.  If you forget the password, you will need to start over with a new set of certificates.';
