<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['user_certificates_app_description'] = 'Certyfikaty zabezpieczeń używane do zabezpieczenia różnych aplikacji, których używasz regularnie.';
$lang['user_certificates_app_name'] = 'Certyfikaty użytkownika';
$lang['user_certificates_certificates'] = 'Certyfikaty';
$lang['user_certificates_certificates_not_available_for_this_account'] = 'Certyfikaty użytkownika nie są dostępne dla tego konta.';
$lang['user_certificates_certificates_not_available_on_this_system'] = 'Przepraszamy, certyfikaty zabezpieczeń nie są dostępne w tym systemie.  Prosimy skontaktować się z administratorem aby uzyskać więcej informacji.';
$lang['user_certificates_certificates_not_enabled_for_your_account'] = 'Przepraszamy, certyfikaty zabezpieczeń nie są włączone dla tego systemu.';
$lang['user_certificates_certificates_not_yet_initialized'] = 'Przepraszamy, certyfikaty zabezpieczeń nie zostały jeszcze zainicjowane.  Prosimy skontaktować się z administratorem aby uzyskać więcej informacji.';
$lang['user_certificates_configuration_file'] = 'Plik konfiguracyjny';
$lang['user_certificates_create_certificates'] = 'Utwórz certyfikaty';
$lang['user_certificates_initialize_certificate_help'] = 'Proszę podać hasło do zabezpieczenie Twoich certyfikatów zabezpieczeń.  Jeżeli zapomnisz hasło, będziesz musiał zacząć od nowa wygenerować certyfikaty.';
